{% set name = "liffile" %}
{% set version = "2025.1.26" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/liffile-{{ version }}.tar.gz
  sha256: a3c53b64bf81692f988c83ecd5f7597ad1c0d77854344d85d4abd8028cf142e4

build:
  entry_points:
    - liffile = liffile.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - tifffile >=2024.8.30
    - xarray >=2023.4.0
    - matplotlib-base >=3.7.0

test:
  imports:
    - liffile
  commands:
    - pip check
    - liffile --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.cgohlke.com
  summary: Read Leica image files (LIF)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cgohlke
